dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.security:spring-security-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j:3.3.0'
//    implementation 'org.springframework.boot:spring-boot-starter-aop'

    asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'

    testImplementation 'com.h2database:h2'
    testImplementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'

    implementation(project(":gh-common"))
    implementation(project(":gh-event"))

    implementation(project(":gh-domain:gh-facility:gh-facility-core"))

    implementation(project(":gh-api-interface:gh-review-api-interface"))
    implementation(project(":gh-api-interface:gh-like-api-interface"))
    implementation(project(":gh-api-interface:gh-file-api-interface"))
    implementation(project(":gh-api-interface:gh-view-api-interface"))

}

jar.enabled = true
