dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.security:spring-security-web'

    asciidoctorExt 'org.springframework.restdocs:spring-restdocs-asciidoctor'

    testImplementation 'com.h2database:h2'
    testImplementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-redis'

    implementation(project(":gh-common"))
    implementation(project(":gh-domain:gh-chat:gh-chat-core"))
    implementation(project(":gh-api-interface:gh-community-api-interface"))


}

jar.enabled = true