name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 21 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 추가
      - name: resources 파일 만들기
        run: mkdir -p gh-application-container/src/main/resources

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > gh-application-container/src/main/resources/application.yml

      # 추가
      - name: gradlew 권한주기
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew :gh-application-container:bootJar

      - name: AWS Resource 에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR 에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t gh-server .

      - name: Docker 이미지에 Tag 붙이기 # ecr 주소값을 태그로
        run: docker tag gh-server ${{ steps.login-ecr.outputs.registry }}/goldenhome-server:latest

      - name: ECR 에 Docker 이미지 Push
        run: docker push ${{ steps.login-ecr.outputs.registry }}/goldenhome-server:latest

      - name: SSH 로 EC2에 접속 및 Docker Compose 배포 # 수정
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true

        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

          script: |
            mkdir -p /home/ubuntu/your-app
            cd /home/ubuntu/your-app
            
            cat <<EOF > docker-compose.yml
            ${{ secrets.DOCKER_COMPOSE_YML }}
            EOF
            
            sed -i "s|\${ECR_REGISTRY}|$ECR_REGISTRY|g" docker-compose.yml
            
            docker-compose down || true 
            docker-compose pull
            docker-compose up -d